server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
lening-service:
  host: localhost
  port: 8082
logging:
  level:
    root: INFO
    nl.bank.vergelijker.vergelijkerservice: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG