server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
lening-service:
  host: localhost
  port: 8080
stubrunner:
  ids: 'nl.bank:levensverzekering-service:+:stubs:8090'
  repositoryRoot: https://repo.spring.io/libs-snapshot
logging:
  level:
    root: INFO
    nl.bank.leningservice: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG